### PR TITLE
Generating for classes with generics (tests)

### PR DESCRIPTION
**Pull request by blipinsk**
Currently the plugin doesn't seem to be working for classes with Generics.

You know the code much better, so I figured that instead of diving really deep into plugin code, I'll just write few tests that currently fail (or at least I believe they fail because I somehow cannot import the code to my IDE). And it should be much better than just submitting an issue.

PS. Out of curiosity: what's your IDE setup for this project?

### CODE REVIEW

**Comment by afcastano** [comment]
Hello,
Thanks for the pull request.
I haven't been able to work on this in the last few months, but now I should have time. I will try to implement this and let you know.

PS. I am putting together a development guideline. It will include IDE set up.

Thanks!

**Comment by blipinsk** [comment]
Cool, thanks! Let me know if (or when 😉) you manage to write this guideline.

I honestly use your plugin all the time (shame it didn't get some more attention). Thanks!

**Comment by afcastano** [comment]
Hi, here is the project set up guideline: https://github.com/afcastano/AutoValuePlugin/blob/master/docs/PROJECT_SETUP.md

I am trying to implement your requirement at the moment. Should be done soon.
Thanks!

**Comment by blipinsk** [comment]
Sounds good, thx!

**Comment by afcastano** [comment]
Hi @blipinsk 
I have just released version 1.0.4 which adds support for generics.
I have merged your tests and they are passing.

Thanks man.
Please let me know if you notice any weird behaviour.

**Comment by blipinsk** [comment]
Awesome Andres!
So you wanna say that my tests were actually working 😄 ?
Thanks!

**Comment by afcastano** [comment]
:) They were! ... with minor adjustments... hehe...
Thanks for that!

**Pull request merged**
